// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCE6wIOVTZIhKAeURxzzc2mU_4Fe_HQZ8',
    appId: '1:329096238857:web:df84a0f5e077166356a5d8',
    messagingSenderId: '329096238857',
    projectId: 'college-gate-dbd50',
    authDomain: 'college-gate-dbd50.firebaseapp.com',
    databaseURL: 'https://college-gate-dbd50-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'college-gate-dbd50.appspot.com',
    measurementId: 'G-EPSXL4FNN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtvTX8omMEKFaIPmR47VTnUXbR04qP0vw',
    appId: '1:329096238857:android:30f8bb30b6acdff556a5d8',
    messagingSenderId: '329096238857',
    projectId: 'college-gate-dbd50',
    databaseURL: 'https://college-gate-dbd50-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'college-gate-dbd50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj7uYViZDYV5XvxiG3epU22_PU4GTporA',
    appId: '1:329096238857:ios:6cbf7f5e2474fa7c56a5d8',
    messagingSenderId: '329096238857',
    projectId: 'college-gate-dbd50',
    databaseURL: 'https://college-gate-dbd50-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'college-gate-dbd50.appspot.com',
    androidClientId: '329096238857-0c2e4mce5dqgvhbraa1qd0fgihm473r6.apps.googleusercontent.com',
    iosClientId: '329096238857-e39neo4lag0j30cqsesdmh7h4snst8ds.apps.googleusercontent.com',
    iosBundleId: 'com.example.collegeGate',
  );
}
